--- #YAML:1.0
name:               Math-SymbolicX-Complex
version:            1.01
abstract:           Complex number support for the Math::Symbolic parser
author:
    - Steffen Mueller <symbolic-module at steffen-mueller dot net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Math::Symbolic:       0.129
    Math::SymbolicX::ParserExtensionFactory:  0.01
    Test::More:           0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
